import type { Product, Review, BlogPost, Category } from "./types";

export const categories: { slug: Category; name: string; description: string; icon: string }[] = [
  { slug: "iso-9001", name: "ISO 9001", description: "Quality Management System documentation", icon: "BadgeCheck" },
  { slug: "iso-14001", name: "ISO 14001", description: "Environmental Management System documentation", icon: "Leaf" },
  { slug: "iso-45001", name: "ISO 45001", description: "Occupational Health & Safety documentation", icon: "HardHat" },
  { slug: "ims", name: "Integrated Management System", description: "Combined QMS + EMS + OHSMS kits", icon: "Layers" },
  { slug: "zed-certification", name: "ZED Certification", description: "Zero Defect Zero Effect starter kits", icon: "Gem" },
  { slug: "vendor-registration", name: "Vendor Registration", description: "Vendor & supplier empanelment documents", icon: "Handshake" },
  { slug: "sops", name: "SOPs", description: "Standard Operating Procedures", icon: "FileStack" },
  { slug: "formats", name: "Formats", description: "Ready-to-use record formats", icon: "FileSpreadsheet" },
  { slug: "audit-checklists", name: "Audit Checklists", description: "Internal & supplier audit checklists", icon: "ClipboardCheck" },
  { slug: "legal-registers", name: "Legal Registers", description: "Applicable legal & statutory registers", icon: "Scale" },
  { slug: "risk-assessment", name: "Risk Assessment", description: "HIRA & risk-opportunity registers", icon: "ShieldAlert" },
  { slug: "calibration", name: "Calibration", description: "Calibration plans & records", icon: "Gauge" },
  { slug: "training", name: "Training", description: "Training plans, matrices & records", icon: "GraduationCap" },
  { slug: "hr-documents", name: "HR Documents", description: "HR policies & personnel formats", icon: "Users" },
  { slug: "quality-documents", name: "Quality Documents", description: "Quality manuals & control plans", icon: "Award" },
  { slug: "environment-documents", name: "Environment Documents", description: "Environmental aspect-impact documents", icon: "TreePine" },
  { slug: "safety-documents", name: "Safety Documents", description: "Safety manuals, posters & permits", icon: "ShieldCheck" },
];

export const products: Product[] = [
  {
    id: "1",
    slug: "iso-9001-2015-complete-documentation-kit",
    title: "ISO 9001:2015 Complete Documentation Kit",
    category: "iso-9001",
    tagline: "Full QMS documentation mapped clause-by-clause",
    description:
      "A complete, editable Quality Management System documentation kit aligned to ISO 9001:2015 clauses. Built by practicing quality consultants for manufacturing, engineering and export businesses preparing for certification or surveillance audits.",
    price: 1500000,
    docCode: "QMS-9001-KIT",
    version: "v1.0",
    lastUpdated: "2026-07-25",
    documentCount: 0,
    whatsIncluded: [
      "Quality Manual (clause-mapped)",
      "Standard Operating Procedures",
      "Record Formats",
      "Internal Audit Checklist",
      "Management Review Agenda & Minutes Template",
    ],
    compatibility: ["MS Word", "MS Excel"],
    images: ["/images/products/iso-9001-1.jpg"],
    rating: 0,
    reviewCount: 0,
    popular: true,
  },
  {
    id: "1a",
    slug: "iso-9001-2015-quality-manual",
    title: "ISO 9001:2015 Quality Manual",
    category: "quality-documents",
    tagline: "Standalone clause-mapped quality manual",
    description:
      "The Quality Manual from the full ISO 9001:2015 kit, sold separately for businesses that only need the top-level manual.",
    price: 300000,
    docCode: "QMS-9001-MANUAL",
    version: "v1.0",
    lastUpdated: "2026-07-25",
    documentCount: 0,
    whatsIncluded: ["Quality Manual (clause-mapped)"],
    compatibility: ["MS Word"],
    images: ["/images/products/iso-9001-1.jpg"],
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "1b",
    slug: "iso-9001-2015-sop-set",
    title: "ISO 9001:2015 SOP Set",
    category: "sops",
    tagline: "Standard Operating Procedures, sold on their own",
    description:
      "The full set of Standard Operating Procedures from the ISO 9001:2015 kit, for businesses that already have a manual but need the procedures.",
    price: 500000,
    docCode: "QMS-9001-SOPS",
    version: "v1.0",
    lastUpdated: "2026-07-25",
    documentCount: 0,
    whatsIncluded: ["Standard Operating Procedures"],
    compatibility: ["MS Word"],
    images: ["/images/products/iso-9001-1.jpg"],
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "1c",
    slug: "iso-9001-2015-internal-audit-checklist",
    title: "ISO 9001:2015 Internal Audit Checklist",
    category: "audit-checklists",
    tagline: "Clause-wise internal audit checklist",
    description:
      "A standalone internal audit checklist mapped to ISO 9001:2015 clauses, with scoring and non-conformance tracking columns.",
    price: 150000,
    docCode: "QMS-9001-AUDCHK",
    version: "v1.0",
    lastUpdated: "2026-07-25",
    documentCount: 0,
    whatsIncluded: ["Internal Audit Checklist"],
    compatibility: ["MS Excel"],
    images: ["/images/products/iso-9001-1.jpg"],
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "1d",
    slug: "iso-9001-2015-record-formats-pack",
    title: "ISO 9001:2015 Record Formats Pack",
    category: "formats",
    tagline: "Ready-to-use record formats",
    description:
      "The full pack of record formats from the ISO 9001:2015 kit, sold separately.",
    price: 250000,
    docCode: "QMS-9001-FMTS",
    version: "v1.0",
    lastUpdated: "2026-07-25",
    documentCount: 0,
    whatsIncluded: ["Record Formats"],
    compatibility: ["MS Word", "MS Excel"],
    images: ["/images/products/iso-9001-1.jpg"],
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "2",
    slug: "iso-14001-2015-ems-documentation-kit",
    title: "ISO 14001:2015 EMS Documentation Kit",
    category: "iso-14001",
    tagline: "Environmental management system, audit-ready",
    description:
      "Editable Environmental Management System documents covering aspect-impact analysis, legal compliance registers, emergency preparedness and monitoring formats for manufacturing facilities.",
    price: 449900,
    compareAtPrice: 699900,
    docCode: "EMS-14001-KIT",
    version: "v3.1",
    lastUpdated: "2026-05-22",
    documentCount: 48,
    whatsIncluded: [
      "Environmental Manual",
      "Aspect-Impact Register Template",
      "34 EMS Procedures",
      "Legal & Other Requirements Register",
      "Emergency Preparedness Plan",
    ],
    compatibility: ["MS Word", "MS Excel", "Google Docs"],
    images: ["/images/products/iso-14001-1.jpg"],
    previewPdfUrl: "/previews/iso-14001-preview.pdf",
    rating: 4.7,
    reviewCount: 132,
    popular: true,
  },
  {
    id: "3",
    slug: "iso-45001-2018-ohsms-documentation-kit",
    title: "ISO 45001:2018 OH&S Documentation Kit",
    category: "iso-45001",
    tagline: "Occupational health & safety management, plant-ready",
    description:
      "A practical OH&S documentation set with hazard identification & risk assessment (HIRA) registers, permit-to-work formats, incident investigation forms and safety training records.",
    price: 449900,
    docCode: "OHS-45001-KIT",
    version: "v2.9",
    lastUpdated: "2026-04-30",
    documentCount: 45,
    whatsIncluded: [
      "OH&S Manual",
      "HIRA Register Template",
      "Permit to Work Formats",
      "Incident Investigation Report",
      "Safety Training Matrix",
    ],
    compatibility: ["MS Word", "MS Excel"],
    images: ["/images/products/iso-45001-1.jpg"],
    rating: 4.9,
    reviewCount: 98,
    popular: true,
  },
  {
    id: "4",
    slug: "integrated-management-system-ims-kit",
    title: "Integrated Management System (IMS) Kit",
    category: "ims",
    tagline: "QMS + EMS + OHSMS in one unified structure",
    description:
      "A single integrated documentation structure covering ISO 9001, ISO 14001 and ISO 45001 together, reducing duplication for companies pursuing combined certification.",
    price: 899900,
    compareAtPrice: 1299900,
    docCode: "IMS-COMBO-KIT",
    version: "v2.0",
    lastUpdated: "2026-06-01",
    documentCount: 110,
    whatsIncluded: ["Integrated Manual", "100+ Procedures & Formats", "Combined Audit Checklist", "Integrated Risk Register"],
    compatibility: ["MS Word", "MS Excel"],
    images: ["/images/products/ims-1.jpg"],
    rating: 4.8,
    reviewCount: 61,
  },
  {
    id: "5",
    slug: "zed-bronze-certification-starter-kit",
    title: "ZED Bronze Certification Starter Kit",
    category: "zed-certification",
    tagline: "Government ZED scheme documentation, simplified",
    description:
      "Documentation kit aligned to Zero Defect Zero Effect (ZED) Bronze parameters, built for MSMEs preparing their self-assessment and desktop assessment submission.",
    price: 249900,
    docCode: "ZED-BRZ-KIT",
    version: "v1.4",
    lastUpdated: "2026-03-18",
    documentCount: 28,
    whatsIncluded: ["ZED Self-Assessment Guide", "Parameter-wise Evidence Formats", "Process Documentation Templates"],
    compatibility: ["MS Word", "MS Excel"],
    images: ["/images/products/zed-1.jpg"],
    rating: 4.6,
    reviewCount: 44,
  },
  {
    id: "6",
    slug: "vendor-registration-document-pack",
    title: "Vendor Registration Document Pack",
    category: "vendor-registration",
    tagline: "Everything buyers ask for at vendor empanelment",
    description:
      "A ready compliance pack of company profile, quality policy, process capability statement and declaration formats commonly requested during vendor registration with OEMs and PSUs.",
    price: 149900,
    docCode: "VEN-REG-PACK",
    version: "v3.0",
    lastUpdated: "2026-02-14",
    documentCount: 20,
    whatsIncluded: ["Company Profile Template", "Quality Policy Draft", "Process Capability Statement", "Self-Declaration Formats"],
    compatibility: ["MS Word"],
    images: ["/images/products/vendor-1.jpg"],
    rating: 4.5,
    reviewCount: 37,
  },
  {
    id: "7",
    slug: "internal-audit-checklist-bundle",
    title: "Internal Audit Checklist Bundle",
    category: "audit-checklists",
    tagline: "Clause-wise checklists for QMS, EMS & OHSMS",
    description:
      "A bundle of internal audit checklists covering ISO 9001, 14001 and 45001 clauses with scoring columns and non-conformance tracking sheets.",
    price: 99900,
    docCode: "AUD-CHK-BND",
    version: "v2.3",
    lastUpdated: "2026-05-05",
    documentCount: 15,
    whatsIncluded: ["QMS Audit Checklist", "EMS Audit Checklist", "OHSMS Audit Checklist", "NC Tracking Sheet"],
    compatibility: ["MS Excel", "Google Sheets"],
    images: ["/images/products/audit-1.jpg"],
    rating: 4.7,
    reviewCount: 76,
    popular: true,
  },
  {
    id: "8",
    slug: "calibration-management-format-pack",
    title: "Calibration Management Format Pack",
    category: "calibration",
    tagline: "Instrument calibration planning & records",
    description: "Calibration schedule, status register and instrument history card formats for measuring and monitoring equipment.",
    price: 79900,
    docCode: "CAL-MGT-PACK",
    version: "v1.6",
    lastUpdated: "2026-01-20",
    documentCount: 9,
    whatsIncluded: ["Calibration Schedule", "Calibration Status Register", "Instrument History Card"],
    compatibility: ["MS Excel"],
    images: ["/images/products/calibration-1.jpg"],
    rating: 4.4,
    reviewCount: 22,
  },
];

export const reviews: Review[] = [
  { id: "r3", productId: "3", name: "Vivek Sharma", company: "Sharma Fabricators", rating: 5, comment: "The HIRA register template alone saved our safety officer days of formatting work.", date: "2026-04-25" },
  { id: "r4", productId: "5", name: "Anita Deshmukh", company: "Deshmukh Exports", rating: 4, comment: "Good starting point for ZED Bronze — we still customised a few sections but the structure was solid.", date: "2026-03-30" },
];

export const blogPosts: BlogPost[] = [
  {
    id: "b1",
    slug: "iso-9001-2015-clause-by-clause-guide",
    title: "ISO 9001:2015 Documentation: A Clause-by-Clause Guide",
    excerpt: "What every clause actually requires in writing — and what auditors check for in practice.",
    category: "ISO Tips",
    coverImage: "/images/blog/clause-guide.jpg",
    author: "ISO Docs Hub Team",
    date: "2026-06-15",
    readMinutes: 8,
  },
  {
    id: "b2",
    slug: "how-to-conduct-an-internal-audit",
    title: "How to Conduct an Internal Audit That Actually Improves Your QMS",
    excerpt: "A practical checklist-driven approach used by consultants during surveillance audit prep.",
    category: "Internal Audit",
    coverImage: "/images/blog/internal-audit.jpg",
    author: "ISO Docs Hub Team",
    date: "2026-06-08",
    readMinutes: 6,
  },
  {
    id: "b3",
    slug: "zed-certification-explained-for-msmes",
    title: "ZED Certification Explained: What MSMEs Need to Know in 2026",
    excerpt: "Bronze, Silver and Gold parameters, subsidy details, and how to prepare your evidence file.",
    category: "ZED",
    coverImage: "/images/blog/zed-explained.jpg",
    author: "ISO Docs Hub Team",
    date: "2026-05-29",
    readMinutes: 7,
  },
  {
    id: "b4",
    slug: "vendor-registration-document-checklist",
    title: "The Document Checklist OEM Buyers Expect at Vendor Registration",
    excerpt: "The nine documents that come up in almost every vendor empanelment review.",
    category: "Vendor Registration",
    coverImage: "/images/blog/vendor-checklist.jpg",
    author: "ISO Docs Hub Team",
    date: "2026-05-11",
    readMinutes: 5,
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}
export function getProductsByCategory(category: Category) {
  return products.filter((p) => p.category === category);
}
export function getReviewsForProduct(productId: string) {
  return reviews.filter((r) => r.productId === productId);
}
export function getRelatedProducts(product: Product, limit = 4) {
  return products.filter((p) => p.category === product.category && p.id !== product.id).slice(0, limit);
}
